from __future__ import annotations

from pp_agent.coding.enforcement import (
    ScopeEnforcementResult,
    enforce_path_scope,
    enforce_structured_changes_scope,
    scope_enforcement_to_context_item,
    scope_enforcement_to_details,
)
from pp_agent.coding.execution import (
    CodingExecutionEvent,
    CodingExecutionSession,
    ExecutionGuardrails,
    attach_write_scope_to_patch_candidate_args,
    coding_session_to_runtime_execution_context,
    coding_execution_session_to_context_item,
    default_execution_guardrails,
    execution_guardrails_to_block,
    execution_guardrails_to_context_item,
    execution_session_to_block,
    start_coding_execution_session,
)
from pp_agent.coding.impact import ChangeImpact, analyze_change_impact, change_impact_to_context_item, change_impact_to_dict
from pp_agent.coding.orchestrator import (
    CodingWorkflow,
    coding_workflow_to_block,
    coding_workflow_to_context_item,
    coding_workflow_to_timeline_blocks,
    prepare_coding_workflow,
)
from pp_agent.coding.planner import PlanStep, TaskPlan, build_task_plan, task_plan_to_context_item, task_plan_to_dict
from pp_agent.coding.repository import RepositoryAnalysis, analyze_repository, repository_analysis_to_context_item
from pp_agent.coding.repository_summary import (
    REPOSITORY_SUMMARY_SCHEMA_VERSION,
    RepositorySummary,
    RepositorySummarySection,
    RepositorySummarySource,
    RepositorySummaryWarning,
    repository_relative_posix_path,
    repository_summary_to_dict,
)
from pp_agent.coding.repository_summary_context import repository_summary_to_context_items
from pp_agent.coding.repository_summary_collector import (
    RepositorySummaryCollectionLimits,
    RepositorySummaryDocument,
    build_repository_summary,
)
from pp_agent.coding.pytest_provenance import (
    InstrumentedValidationCommand,
    PytestProvenanceRequest,
    PytestProvenanceVerification,
    build_instrumented_validation_command,
    logical_command_digest,
    verify_pytest_provenance_attestation,
    write_pytest_provenance_attestation,
)
from pp_agent.coding.runtime_loop import (
    ControlledLoopOptions,
    ControlledToolLoopResult,
    collect_pending_approvals,
    controlled_loop_result_to_block,
    controlled_loop_result_to_context_item,
    controlled_loop_result_to_summary,
    default_controlled_loop_options,
    run_controlled_coding_loop,
)
from pp_agent.coding.scoped_activation import (
    ScopedInstructionActivationRecord,
    ScopedInstructionActivationState,
    concrete_task_scope_targets,
)
from pp_agent.coding.scoped_instruction import (
    ScopedInstruction,
    ScopedInstructionResolution,
    ScopedInstructionWarning,
    resolve_scoped_instructions,
)
from pp_agent.coding.scoped_instruction_context import (
    scoped_instruction_context_render_key,
    scoped_instruction_records_to_context_items,
)
from pp_agent.coding.scope import (
    ScopeCheckResult,
    TaskScope,
    build_task_scope,
    check_path_in_scope,
    check_structured_changes_in_scope,
    task_scope_to_context_item,
    task_scope_to_dict,
    task_scope_to_write_scope,
)
from pp_agent.coding.testing import (
    ValidationCommand,
    ValidationPlan,
    build_validation_plan,
    validation_plan_to_context_item,
    validation_plan_to_dict,
)
from pp_agent.coding.validation_execution import (
    ValidationCycleResult,
    approve_staged_validation_cycle,
    reject_staged_validation_cycle,
    stage_validation_cycle,
)
from pp_agent.coding.validation_outcome import (
    SelectedValidationCommand,
    ValidationObservation,
    ValidationOutcome,
    select_primary_pytest_validation_command,
    validation_observation_from_result_details,
    validation_outcome_from_observation,
)

__all__ = [
    "ChangeImpact",
    "CodingExecutionEvent",
    "CodingExecutionSession",
    "CodingWorkflow",
    "ControlledLoopOptions",
    "ControlledToolLoopResult",
    "ExecutionGuardrails",
    "InstrumentedValidationCommand",
    "PlanStep",
    "PytestProvenanceRequest",
    "PytestProvenanceVerification",
    "RepositoryAnalysis",
    "RepositorySummary",
    "RepositorySummaryCollectionLimits",
    "RepositorySummaryDocument",
    "RepositorySummarySection",
    "RepositorySummarySource",
    "RepositorySummaryWarning",
    "REPOSITORY_SUMMARY_SCHEMA_VERSION",
    "ScopeCheckResult",
    "ScopeEnforcementResult",
    "ScopedInstructionActivationRecord",
    "ScopedInstructionActivationState",
    "ScopedInstruction",
    "ScopedInstructionResolution",
    "ScopedInstructionWarning",
    "TaskScope",
    "TaskPlan",
    "ValidationCommand",
    "ValidationCycleResult",
    "SelectedValidationCommand",
    "ValidationObservation",
    "ValidationOutcome",
    "ValidationPlan",
    "analyze_change_impact",
    "analyze_repository",
    "attach_write_scope_to_patch_candidate_args",
    "approve_staged_validation_cycle",
    "build_validation_plan",
    "build_repository_summary",
    "build_instrumented_validation_command",
    "build_task_plan",
    "build_task_scope",
    "check_path_in_scope",
    "check_structured_changes_in_scope",
    "change_impact_to_context_item",
    "change_impact_to_dict",
    "coding_workflow_to_block",
    "coding_workflow_to_context_item",
    "coding_workflow_to_timeline_blocks",
    "coding_session_to_runtime_execution_context",
    "coding_execution_session_to_context_item",
    "collect_pending_approvals",
    "controlled_loop_result_to_block",
    "controlled_loop_result_to_context_item",
    "controlled_loop_result_to_summary",
    "concrete_task_scope_targets",
    "default_execution_guardrails",
    "default_controlled_loop_options",
    "enforce_path_scope",
    "enforce_structured_changes_scope",
    "execution_guardrails_to_block",
    "execution_guardrails_to_context_item",
    "execution_session_to_block",
    "prepare_coding_workflow",
    "repository_analysis_to_context_item",
    "repository_relative_posix_path",
    "repository_summary_to_context_items",
    "repository_summary_to_dict",
    "resolve_scoped_instructions",
    "reject_staged_validation_cycle",
    "run_controlled_coding_loop",
    "scope_enforcement_to_context_item",
    "scope_enforcement_to_details",
    "scoped_instruction_context_render_key",
    "scoped_instruction_records_to_context_items",
    "start_coding_execution_session",
    "stage_validation_cycle",
    "task_plan_to_context_item",
    "task_plan_to_dict",
    "task_scope_to_context_item",
    "task_scope_to_dict",
    "task_scope_to_write_scope",
    "logical_command_digest",
    "select_primary_pytest_validation_command",
    "validation_observation_from_result_details",
    "validation_outcome_from_observation",
    "validation_plan_to_context_item",
    "validation_plan_to_dict",
    "verify_pytest_provenance_attestation",
    "write_pytest_provenance_attestation",
]
