from __future__ import annotations

import warnings
from typing import Any, Optional

from pydantic import BaseModel, Field, model_validator


ANALYSIS_HINTS_DEPRECATED_SINCE = "0.3.0"
ANALYSIS_HINTS_REMOVAL_TARGET = "0.4.0"


class AnalysisHintsDeprecationWarning(UserWarning):
    """Registration-time warning for deprecated legacy analysis_hints."""


LEGACY_ANALYSIS_HINT_ALLOWLIST = {
    "requests_network",
    "touches_external",
    "destructive_hint",
    "protected_path_hint",
    "touches_workspace",
}

LEGACY_ANALYSIS_HINT_DENYLIST = {
    "risk_class",
    "summary",
    "confidence_score",
    "confidence_band",
    "known_safe_inspect",
    "exact_effect_mode",
    "supports_exact_effect_staging",
}

LEGACY_ANALYSIS_HINT_ALIAS_DENYLIST = {
    "safe": "Use explicit declarations instead. Safe/allow semantics are no longer expressed through analysis_hints.",
    "allow": "Use explicit declarations instead. Safe/allow semantics are no longer expressed through analysis_hints.",
    "read_only": "Use non_side_effectful=True and, when appropriate, known_safe_inspect=True.",
    "inspect_only": "Use known_safe_inspect=True and non_side_effectful=True instead.",
    "stageable": "Use exact_effect_mode instead. Staging capability is no longer declared through analysis_hints.",
    "approval_supported": "Use exact_effect_mode instead. Approval capability is no longer declared through analysis_hints.",
    "exact_effect_supported": "Use exact_effect_mode instead. Exact-effect capability is no longer declared through analysis_hints.",
    "confidence": "Confidence is now derived by shared analysis and cannot be author-specified.",
    "safety_score": "Confidence is now derived by shared analysis and cannot be author-specified.",
    "display_summary": "Summary is now generated by stable effect analysis and cannot be author-specified.",
}

_LEGACY_HINT_MIGRATIONS = {
    "risk_class": "Use explicit declarations plus runtime analysis; risk_class is no longer author-declared.",
    "summary": "Use the tool name and description; summary is now generated by stable effect analysis.",
    "confidence_score": "Confidence is now derived by shared analysis and cannot be author-specified.",
    "confidence_band": "Confidence bands are derived by shared analysis and cannot be author-specified.",
    "known_safe_inspect": "Use the explicit known_safe_inspect registration field instead.",
    "exact_effect_mode": "Use the explicit exact_effect_mode registration field instead.",
    "supports_exact_effect_staging": "Do not set supports_exact_effect_staging directly; exact_effect_mode is the primary declaration.",
}


def _analysis_hint_error(key: str, message: str) -> str:
    return (
        f"analysis_hints['{key}'] is no longer allowed as a primary semantics source as of v{ANALYSIS_HINTS_DEPRECATED_SINCE}. "
        f"{message} Removal target: v{ANALYSIS_HINTS_REMOVAL_TARGET}."
    )


def _analysis_hint_warning(key: str) -> str:
    return (
        f"analysis_hints['{key}'] is deprecated as of v{ANALYSIS_HINTS_DEPRECATED_SINCE} and will be removed in v{ANALYSIS_HINTS_REMOVAL_TARGET}. "
        "Legacy analysis_hints are compatibility-only and may only tighten risk. "
        f"Prefer explicit declaration fields such as requests_network_hint or touches_external_hint instead."
    )


def _validate_tightening_hint_value(key: str, value: Any) -> None:
    if not isinstance(value, bool) or value is not True:
        raise ValueError(
            f"analysis_hints['{key}'] only accepts the tightening value True as of v{ANALYSIS_HINTS_DEPRECATED_SINCE}. "
            "Legacy analysis_hints may only mark additional risk and may not express safe or widening semantics. "
            f"Removal target: v{ANALYSIS_HINTS_REMOVAL_TARGET}."
        )


class ToolMetadata(BaseModel):
    name: str
    category: str
    requires_confirmation: bool = False
    permission_domain: str = "read"
    sensitive: bool = False
    model_callable: bool = True
    tool_family: Optional[str] = None
    analysis_hints: dict[str, object] = Field(default_factory=dict)
    legacy_hint_origin: str = "author"
    exact_effect_mode: str = "auto"
    non_side_effectful: bool = False
    known_safe_inspect: bool = False
    requests_network_hint: bool = False
    touches_external_hint: bool = False

    @model_validator(mode="after")
    def _validate_dynamic_declarations(self) -> "ToolMetadata":
        if self.legacy_hint_origin not in {"author", "runtime_internal"}:
            raise ValueError("legacy_hint_origin must be one of: author, runtime_internal")
        if self.exact_effect_mode not in {"none", "auto", "required"}:
            raise ValueError("exact_effect_mode must be one of: none, auto, required")
        if self.known_safe_inspect and not self.non_side_effectful:
            raise ValueError("known_safe_inspect requires non_side_effectful=True")
        if self.known_safe_inspect and self.requests_network_hint:
            raise ValueError("known_safe_inspect cannot be combined with requests_network_hint=True")
        if self.known_safe_inspect and self.touches_external_hint:
            raise ValueError("known_safe_inspect cannot be combined with touches_external_hint=True")
        invalid_alias_hints = sorted(key for key in self.analysis_hints if key in LEGACY_ANALYSIS_HINT_ALIAS_DENYLIST)
        if invalid_alias_hints:
            key = invalid_alias_hints[0]
            raise ValueError(_analysis_hint_error(key, LEGACY_ANALYSIS_HINT_ALIAS_DENYLIST[key]))
        invalid_primary_hints = sorted(key for key in self.analysis_hints if key in LEGACY_ANALYSIS_HINT_DENYLIST)
        if invalid_primary_hints:
            key = invalid_primary_hints[0]
            raise ValueError(_analysis_hint_error(key, _LEGACY_HINT_MIGRATIONS.get(key, "Remove this legacy hint and use explicit declarations instead.")))
        unsupported_hints = sorted(
            key
            for key in self.analysis_hints
            if key not in LEGACY_ANALYSIS_HINT_ALLOWLIST
            and key not in LEGACY_ANALYSIS_HINT_DENYLIST
            and key not in LEGACY_ANALYSIS_HINT_ALIAS_DENYLIST
        )
        if unsupported_hints:
            allowed = ", ".join(sorted(LEGACY_ANALYSIS_HINT_ALLOWLIST))
            raise ValueError(
                f"analysis_hints['{unsupported_hints[0]}'] is not supported. "
                f"Legacy analysis_hints are compatibility-only and may only use: {allowed}. "
                f"Deprecated since v{ANALYSIS_HINTS_DEPRECATED_SINCE}; removal target v{ANALYSIS_HINTS_REMOVAL_TARGET}."
            )
        for key, value in self.analysis_hints.items():
            _validate_tightening_hint_value(key, value)
        if self.analysis_hints and self.legacy_hint_origin == "author":
            warned_keys = ", ".join(sorted(self.analysis_hints))
            warnings.warn(
                f"{_analysis_hint_warning(warned_keys)}",
                AnalysisHintsDeprecationWarning,
                stacklevel=2,
            )
        return self

    @property
    def supports_exact_effect_staging(self) -> bool:
        return self.exact_effect_mode in {"auto", "required"}

    @property
    def has_explicit_dynamic_declarations(self) -> bool:
        return self.exact_effect_mode == "required" or any(
            (
                self.non_side_effectful,
                self.known_safe_inspect,
                self.requests_network_hint,
                self.touches_external_hint,
            )
        )

    @property
    def uses_legacy_analysis_hints(self) -> bool:
        return bool(self.analysis_hints)

    @property
    def counts_toward_removal_blocker(self) -> bool:
        return self.uses_legacy_analysis_hints and self.legacy_hint_origin == "author"

    @property
    def declaration_strength(self) -> str:
        if self.has_explicit_dynamic_declarations:
            return "declared"
        if self.uses_legacy_analysis_hints:
            return "legacy_only"
        return "weak"
